Fix pretty_format value from pike cinder show volume table
This change handles volume_image_metadata due to cinderclient change
in pike. It fixes the following issue affecting multiple automation
TCs in Pike.

Error message in automation output:
>           image_name = eval(image_meta_data)['image_name']
 TypeError: eval() arg 1 must be a string, bytes or code object
    keywords/nova_helper.py:1122: TypeError